// <auto-generated />
using System;
using System.Collections.Generic;
using GitDevelop.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitDevelop.Infrastructure.Migrations
{
    [DbContext(typeof(GitDevelopDbContext))]
    partial class GitDevelopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitDevelop.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Password", "GitDevelop.Domain.Accounts.Account.Password#Password", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("HashedValue")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("password_hash");
                        });

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_email");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Blob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("HashValue")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Hash", "GitDevelop.Domain.GitObjects.Blob.Hash#ContentHash", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte[]>("Value")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(32)
                                .HasColumnType("bytea")
                                .HasColumnName("hash");
                        });

                    b.HasKey("Id")
                        .HasName("pk_blobs");

                    b.HasIndex("HashValue")
                        .IsUnique()
                        .HasDatabaseName("ux_blobs_hash");

                    b.ToTable("blobs", (string)null);
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("HeadCommitId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_commit_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("HeadCommitId");

                    b.HasIndex("DocumentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_document_name");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Commit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<byte[]>("HashValue")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<Guid>("RootTreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_tree_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Hash", "GitDevelop.Domain.GitObjects.Commit.Hash#ContentHash", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte[]>("Value")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(32)
                                .HasColumnType("bytea")
                                .HasColumnName("hash");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Message", "GitDevelop.Domain.GitObjects.Commit.Message#CommitMessage", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("message");
                        });

                    b.HasKey("Id")
                        .HasName("pk_commits");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_commits_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_commits_created_at");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_commits_repository_id");

                    b.HasIndex("HashValue")
                        .IsUnique()
                        .HasDatabaseName("ux_commits_hash");

                    b.HasIndex("RootTreeId");

                    b.ToTable("commits", (string)null);
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranchName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("default_branch_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Tree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<byte[]>("HashValue")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Hash", "GitDevelop.Domain.GitObjects.Tree.Hash#ContentHash", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte[]>("Value")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(32)
                                .HasColumnType("bytea")
                                .HasColumnName("hash");
                        });

                    b.HasKey("Id")
                        .HasName("pk_trees");

                    b.HasIndex("HashValue")
                        .IsUnique()
                        .HasDatabaseName("ux_trees_hash");

                    b.ToTable("trees", (string)null);
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Branch", b =>
                {
                    b.HasOne("GitDevelop.Domain.GitObjects.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_document");

                    b.HasOne("GitDevelop.Domain.GitObjects.Commit", null)
                        .WithMany()
                        .HasForeignKey("HeadCommitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_head_commit");
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Commit", b =>
                {
                    b.HasOne("GitDevelop.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commits_account");

                    b.HasOne("GitDevelop.Domain.GitObjects.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commits_repository");

                    b.HasOne("GitDevelop.Domain.GitObjects.Tree", null)
                        .WithMany()
                        .HasForeignKey("RootTreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commits_root_tree");

                    b.OwnsMany("GitDevelop.Domain.GitObjects.CommitParent", "ParentIds", b1 =>
                        {
                            b1.Property<Guid>("commit_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ParentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("parent_id");

                            b1.HasKey("commit_id", "ParentId");

                            b1.HasIndex("ParentId")
                                .HasDatabaseName("ix_commit_parents_parent_id");

                            b1.ToTable("commit_parents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("commit_id");
                        });

                    b.Navigation("ParentIds");
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Document", b =>
                {
                    b.OwnsOne("GitDevelop.Domain.GitObjects.DocumentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("metadata_description");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("metadata_title");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");

                            b1.OwnsMany("GitDevelop.Domain.GitObjects.DocumentTag", "Tags", b2 =>
                                {
                                    b2.Property<Guid>("document_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("tag");

                                    b2.HasKey("document_id", "Value");

                                    b2.ToTable("document_tags", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("document_id");
                                });

                            b1.Navigation("Tags");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("GitDevelop.Domain.GitObjects.Tree", b =>
                {
                    b.OwnsMany("GitDevelop.Domain.GitObjects.TreeEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("tree_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("name");

                            b1.Property<string>("ObjectId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("object_id");

                            b1.HasKey("tree_id", "id")
                                .HasName("pk_tree_entries");

                            b1.HasIndex("tree_id", "Name")
                                .IsUnique()
                                .HasDatabaseName("ix_tree_entries_tree_name");

                            b1.ToTable("tree_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("tree_id");
                        });

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
