// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VcsDevelop.Infrastructure.DbContexts;

#nullable disable

namespace VcsDevelop.Infrastructure.Migrations
{
    [DbContext(typeof(VcsDevelopDbContext))]
    [Migration("20260415174437_MakeDocumentMetadataPropertyNullable")]
    partial class MakeDocumentMetadataPropertyNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VcsDevelop.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Password", "VcsDevelop.Domain.Accounts.Account.Password#Password", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("HashedValue")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("password_hash");
                        });

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_email");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Blob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_blobs");

                    b.ToTable("blobs", (string)null);
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("HeadCommitId")
                        .IsRequired()
                        .HasColumnType("char(40)")
                        .HasColumnName("head_commit_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("HeadCommitId");

                    b.HasIndex("DocumentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_document_name");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Commit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(40)")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("RootTreeId")
                        .IsRequired()
                        .HasColumnType("char(40)")
                        .HasColumnName("root_tree_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Message", "VcsDevelop.Domain.VcsObjects.Commit.Message#CommitMessage", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("message");
                        });

                    b.HasKey("Id")
                        .HasName("pk_commits");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_commits_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_commits_created_at");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_commits_document_id");

                    b.HasIndex("RootTreeId");

                    b.ToTable("commits", (string)null);
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranchName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("default_branch_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_documents_owner_id_name");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Tree", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(40)")
                        .HasColumnName("tree_id");

                    b.HasKey("Id")
                        .HasName("pk_trees");

                    b.ToTable("trees", (string)null);
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Branch", b =>
                {
                    b.HasOne("VcsDevelop.Domain.VcsObjects.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_document");

                    b.HasOne("VcsDevelop.Domain.VcsObjects.Commit", null)
                        .WithMany()
                        .HasForeignKey("HeadCommitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_head_commit");
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Commit", b =>
                {
                    b.HasOne("VcsDevelop.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commits_account");

                    b.HasOne("VcsDevelop.Domain.VcsObjects.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commits_document");

                    b.HasOne("VcsDevelop.Domain.VcsObjects.Tree", null)
                        .WithMany()
                        .HasForeignKey("RootTreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commits_root_tree");

                    b.OwnsMany("VcsDevelop.Domain.VcsObjects.CommitParent", "ParentIds", b1 =>
                        {
                            b1.Property<string>("commit_id")
                                .HasColumnType("char(40)");

                            b1.Property<string>("ParentId")
                                .HasColumnType("text")
                                .HasColumnName("parent_id");

                            b1.HasKey("commit_id", "ParentId");

                            b1.HasIndex("ParentId")
                                .HasDatabaseName("ix_commit_parents_parent_id");

                            b1.ToTable("commit_parents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("commit_id");
                        });

                    b.Navigation("ParentIds");
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Document", b =>
                {
                    b.HasOne("VcsDevelop.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_accounts_owner_id");

                    b.OwnsOne("VcsDevelop.Domain.VcsObjects.DocumentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("metadata_description");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("metadata_title");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");

                            b1.OwnsMany("VcsDevelop.Domain.VcsObjects.DocumentTag", "Tags", b2 =>
                                {
                                    b2.Property<Guid>("document_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("tag");

                                    b2.HasKey("document_id", "Value");

                                    b2.ToTable("document_tags", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("document_id");
                                });

                            b1.Navigation("Tags");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("VcsDevelop.Domain.VcsObjects.Tree", b =>
                {
                    b.OwnsMany("VcsDevelop.Domain.VcsObjects.TreeEntry", "Entries", b1 =>
                        {
                            b1.Property<string>("tree_id")
                                .HasColumnType("char(40)");

                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("name");

                            b1.Property<string>("ObjectId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("object_id");

                            b1.HasKey("tree_id", "id")
                                .HasName("pk_tree_entries");

                            b1.HasIndex("tree_id", "Name")
                                .IsUnique()
                                .HasDatabaseName("ix_tree_entries_tree_name");

                            b1.ToTable("tree_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("tree_id");
                        });

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
